# Generated by Django 4.2.2 on 2023-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='Cover Image'),
        ),
    ]
