# Generated by Django 4.2.2 on 2023-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_cover_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
    ]
