# Generated by Django 4.2.2 on 2023-06-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_visitlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-create_at', '-update_at'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-create_at'], 'verbose_name': 'Visit Log', 'verbose_name_plural': 'Visit Logs'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='qr_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.profile', verbose_name='Visited Profile'),
        ),
    ]
