# Generated by Django 4.2.2 on 2023-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sociallink_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Public'),
        ),
    ]
