# Generated by Django 4.2.2 on 2023-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='hide_from_profile',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Hide From Profile'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='hide_from_visitor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Hide From Visitor'),
        ),
    ]
