# Generated by Django 4.2.2 on 2023-08-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_visitlog_hide_from_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
    ]
