# Generated by Django 4.2.2 on 2023-06-23 22:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cookie Policy',
                'verbose_name_plural': 'Cookie Policy',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=1000, verbose_name='Quote')),
                ('quote_en', models.CharField(max_length=1000, null=True, verbose_name='Quote')),
                ('quote_ar', models.CharField(max_length=1000, null=True, verbose_name='Quote')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ar', models.TextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
            },
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, verbose_name='Alternative (Alt)')),
                ('alt_en', models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, null=True, verbose_name='Alternative (Alt)')),
                ('alt_ar', models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, null=True, verbose_name='Alternative (Alt)')),
                ('image', models.ImageField(upload_to='home/header', verbose_name='Image')),
                ('active', models.BooleanField(default=True, help_text='Setting it to false, makes the image disappear from homepage', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Home Page Image',
                'verbose_name_plural': 'Home Page Images',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='Facebook Link')),
                ('instagram', models.URLField(verbose_name='Instagram Link')),
                ('twitter', models.URLField(verbose_name='Twitter Link')),
                ('telegram', models.URLField(verbose_name='Telegram Link')),
                ('email', models.EmailField(max_length=254, verbose_name='Web Email')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Whatsapp Number')),
                ('why_us', models.TextField(null=True, verbose_name='Why do you choose us?')),
                ('why_us_en', models.TextField(null=True, verbose_name='Why do you choose us?')),
                ('why_us_ar', models.TextField(null=True, verbose_name='Why do you choose us?')),
            ],
            options={
                'verbose_name': 'Website Main Info',
                'verbose_name_plural': 'Website Main Info',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ar', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Terms Of Service',
                'verbose_name_plural': 'Terms Of Service',
            },
        ),
    ]
