# Generated by Django 4.2.2 on 2023-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
